name: Frontend CI

on:
  push:
    paths:
      - frontend/**
  pull_request:
    paths:
      - frontend/**
    branches:
      - main

permissions:
  contents: read

jobs:
  compile-contracts:
    name: Compile solidity contracts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Compile contracts
        run: npm run compile
      
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-contracts
          path: ${{ github.workspace }}/frontend/src/artifacts

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: compile-contracts
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Download compiled contracts
        uses: actions/download-artifact@v4
        with:
          name: compiled-contracts
          path: ${{ github.workspace }}/frontend/src/artifacts

      - name: Build project
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: ${{ github.workspace }}/frontend/dist/

  lint:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Lint project
        run: npm run lint